describe('Backgrondtest', function() {
    it('Background verification of data', function() {
      cy.visit('https://stgapplicant.vetty.co/login')
      cy.get("#email").type("shweta.applicant+280@gmail.com")
      cy.get("#ssn").type("123456")
      cy.get(".form-control").click()
      cy.screenshot()
      cy.wait(4000)
      cy.get("#firstname").clear().type("Tejaswini")
      cy.get("#middlename").clear().type("ganuga")
      cy.get("#lastname").clear().type("Srinivasulu")
      cy.get("[placeholder='mm/dd/yyyy']").clear().type("08/05/1997")
      cy.get("#ssn").clear().type("234551234")
      cy.get("[name='street']").clear().type("Andhra")
      cy.get("#zip").clear().type("12345")
      cy.get("#city").clear().type("sammohan")
      cy.get("#state").select("Nevada")
      cy.get("#phone").clear().type("9440888908")
      cy.get("body > app-root > div > app-applicant-details > div > div > div > app-background-check > form > div > div.form-box.calforniaWrap > div:nth-child(2) > div:nth-child(2) > div > div").click()
      cy.get(".white-btn").click()
      cy.screenshot()
      cy.visit("https://stgapplicant.vetty.co/applicant-details/disclosures")
      cy.get(".btnDefault").click()
      cy.go("forward")
      cy.get(".btnDefault").click()
      cy.go("forward")
      cy.wait(4000)
      cy.get("/html/body/app-root/div/app-applicant-details/div/div/div/app-disclosure-agreement/div[1]/div[1]/app-disclosure/div[3]/div[1]/div[1]/div[2]/signature-pad/canvas").click()
      cy.get("#printedName").type("Tejaswini ganuga Srinivasulu") 
      cy.get("[type='checkbox']").check().should('be.checked').and('have.value','I consent to the background checks and indicate my agreement to all of the above.')
      cy.screenshot()  
      cy.get(".btnDefault").click()
    })
  })